### ISSUE TITLE
Hi Dan, I'm HongKonger, please do not work in China

### ISSUE THREAD

**Issue by taomanwai** [danpovey/danielpovey#1]
Culture differences are huge, even it's compared with Hong Kong / Taiwan.

1. Unrealistic KPI, and if you do not obey or trying to discuss, you will be labelled as having loyalty issue.
2. Chinese Companies tend to treat people as machine.
3. Poisoned food everywhere without regulations at all. It may affect your long term health
4. Mainland Chinese hates foreigners in deep heart rather than loves them (especially for people who loves the country or Communist Party very much), they tends to "steal" foreigners technology and then say goodbye to you. They think it is an honor to do so.

**Comment by danpovey** [comment]
Thanks for your comment... still deciding.  May even end up in HK but not sure.
